export const CREATE_ITEM_ACTIVE = 'CREATE_ITEM_ACTIVE';
export const CREATE_ITEM_CHANGE_VALUE = 'CREATE_ITEM_CHANGE_VALUE';
export const CREATE_ITEM_SAVE = 'CREATE_ITEM_SAVE';
export const CREATE_ITEM_NEW_ITEM = 'CREATE_ITEM_NEW_ITEM';